### PR TITLE
Increased max length of charfields in model and db

### PR DESCRIPTION
**Pull request by VirtualSatai**
SQLite doesn't check this, right now some of our testdata is incompatible with MySQL since it does enforce the max_length. Also there are no real reasons for these arbitrary limitations.

### CODE REVIEW

**Comment by VirtualSatai** [comment]
Also migrations are technically tested, and therefore increased our test coverage. I'll be looking into this.

**Comment by fishbacon** [comment]
I want to see novels published trough stregsystem products.

**Comment by VirtualSatai** [comment]
If nothing else, now it's easier to embed images in the name of products 🤔

**Comment by fishbacon** [comment]
well injecting html is still possible so...

**Comment by VirtualSatai** [comment]
It's a feature!

**Comment by fishbacon** [comment]
> It's a feature!

I am pretty sure we would get some serious pushback from the treo if we suggested not having this feature.

**Pull request merged**
