### PR TITLE
Removed shaming template from user menu page

### LINKED ISSUE #322: Don't shame for not using multibuy when buying from user profile
Currently if you type "Username" and then click the any product twice, you'll be shamed for not using multibuy, which is not possible through your profile.

### PR DESCRIPTION
**Pull request by patrickreiffenstein**
Just removed a code stump that shamed people.
Closes #322

### CODE REVIEW

**Review by falkecarlsen — CHANGES_REQUESTED** [review]
This is a feature to let people know that multibuy exists, since many people does not know it does.

**Comment by patrickreiffenstein** [comment]
> This is a feature to let people know that multibuy exists, since many people does not know it does.

This is only the removal of multibuy shaming in the user menu, where you can't multibuy anyway.

**Comment by krestenlaust** [comment]
billede
Multibuy message still works on the frontpage (I've setup this branch locally)

**Review by krestenlaust — APPROVED** [review]

**Review by falkecarlsen — APPROVED** [review]
:shipit:

**Pull request merged**
