### PR TITLE
Partial autofocus, at least on the menu.html page

### PR DESCRIPTION
**Pull request by DelusionalLogic**
I guess you can access the "restart" link with Alt+q (Alt+Shift+q in
firefox). Maybe this is sufficient?

### CODE REVIEW

**Comment by hrjakobsen** [comment]
Is this not a bit of an overkill for focusing a single element? Would it not be enough to make sure that the link is the first element in the tab-ordering?
If we change the link to `<a tabindex="1" href="/{{room.id}}/user/{{member.id}}">Bruger Info</a>`, it will be the first element focused when pressing tab.

**Comment by DelusionalLogic** [comment]
It's a lot of "code" for very little functionality now. I argue it isn't a problem, since none of the code is actually active nor requires support.

It's also important to note that this feature is a direct response to a request by a member. What the member wanted was to be able to just always click enter to return to the main page. I tried to make this happen, but I'm having trouble doing so with the restart button since it's in the base package.

There's some stuff we can do, but this is a first step.

**Comment by kimsey0** [comment]
If you're going to merge this sometime, may I suggest changing from using the id `autofocus` to using the same `autofocus` attribute as for input elements? `document.getElementById("autofocus")` can just be changed to `document.querySelector("[autofocus]")`.

**Comment by hrjakobsen** [comment]
I think we have moved with other solutions than this, and as such I will close this PR.

**Pull request closed without merging**
