### PR TITLE
Optimised easter animation

### PR DESCRIPTION
**Pull request by klem-bot-delta**
+ Switched beerflakes from GIFs to CSS animations
+ Removed redundant JS code by using a ternary
+ Switched cursed beerflakes to using a modifier CSS class instead of a dedicated function
+ Moved some CSS styles from JS to the CS

### CODE REVIEW

**Comment by atjn** [comment]
I am working on some more optimizations to the CSS and JS for the entire frontend. Some of my optimizations are almost identical to the ones in this PR. Is it possible to get this merged, or alternatively, have your blessing to duplicate these changes in my PR?

**Review by Nielswps — APPROVED** [review]
Could be nice to have the optimizations merged before easter :hatching_chick:

**Review by JakobTopholt — APPROVED** [review]
lgtm

**Review by JakobTopholt — APPROVED** [review]
Still lgtm

**Comment by krestenlaust** [comment]
Merged before easter 👍

**Pull request merged**
