### PR TITLE
Limit number of bats

### PR DESCRIPTION
**Pull request by hrjakobsen**
The Pi and laptops cannot handle even 8 bats, they will be useless with 30 bats.

### CODE REVIEW

**Comment by VirtualSatai** [comment]
I dislike this change

**Comment by hrjakobsen** [comment]
Then you should donate the raspberry pi this time 😂

**Comment by DelusionalLogic** [comment]
Please revert this. My workflow depended in the number of bats. Now that there's too few bats, chrome doesn't eat as much memory. With chrome not eating memory, the OOM Reaper doesn't kill the processes i need killed periodically.

I guess you don't care about your downstream users :kaaba:

**Comment by hrjakobsen** [comment]
I think we should we should use `log2(day)` instead of limiting it to two. Then it would still scale with days but hopefully not kill the Pi.

**Pull request merged**
