### PR TITLE
Fnugfald razzia

### PR DESCRIPTION
**Pull request by krestenlaust**
People shan't get beer more often than every 30 minutes, and people need to have bought a ticket.

Related to #330

### CODE REVIEW

**Review by Nobogo — APPROVED** [review]
Kinda bad, we need it tomorrow though, please be "temporary"

**Comment by LucasWedel** [comment]
aint no way vi bliver øl-ratelimited på 2 i timen??

**Comment by krestenlaust** [comment]
> @LucasWedel aint no way vi bliver øl-ratelimited på 2 i timen??

Don't kill the bødel. Standard foobar procedure 🙃 you're welcome to question their methods at foobar[at]fklub.dk

**Comment by LucasWedel** [comment]
> > @LucasWedel aint no way vi bliver øl-ratelimited på 2 i timen??
> 
> @krestenlaust  Don't kill the bødel. Standard foobar procedure 🙃 you're welcome to question their methods at foobar[at]fklub.dk

Me angery, me unhappy, me thirsty >:(

**Review by falkecarlsen — APPROVED** [review]
In practice 2 beers and hour has angered very few since I implemented it originally last year https://github.com/f-klubben/stregsystemet/blob/next/stregreport/views.py#L62.

:shipit:

**Pull request merged**
