### PR TITLE
More bats

### PR DESCRIPTION
**Pull request by AndersSpringborg**
As the system now runs on mobile phones, the client do not crash with an increase of bats on the screen. Trippling the amount of bats, seems reasonable

### CODE REVIEW

**Comment by hrjakobsen** [comment]
Let's spawn 2^n bats instead

**Comment by AndersSpringborg** [comment]
agree

**Comment by BoAnd** [comment]
Hey guys. 

The only correct algorithm to this problem. Would be the Ackermann function.
Where A(d.getMonth(), d.getDate())

**Comment by hrjakobsen** [comment]
My brain hurts just looking at the definition of that function 

Ackermann function on Wikipedia

**Review by cogitantium — COMMENTED** [review]
I tried to run it with 2^30 bats but even though I [downloaded more ram](https://downloadram.net/) it still hung my machine. Maybe a larger number of bats would help?

**Comment by AndersSpringborg** [comment]
Maybe i would help with an extra graphic, so the bats would't be so lonely

**Pull request closed without merging**
