### PR TITLE
Extract email templates into separate files

### LINKED ISSUE #331: Extract email templates into individual template files
There are email templates included directly in the code in `stregsystem/utils.py` and `stregsystem/mail.py`, respectively the balance updated and welcome email are in these files.
It would make more sense to extract all communication templates into individual html files in a new directory in the templates folder.

### PR DESCRIPTION
**Pull request by krestenlaust**
Resolves #331

- [x] Welcome mail (`mail.py`)
- [x] Deposited stregdollars (`utils.py`)
- [x] Deposited stregdollars (shame) (`utils.py`)

I'm using djangos templating engine.

Not sure about how to organize the new files, I've just named the folder `message_templates` (in case we want to implement something like push notifications in the future😉)

### CODE REVIEW

**Comment by jonasKjellerup** [comment]
Consider putting the templates in `stregsystem/templates/mail` instead.

**Comment by krestenlaust** [comment]
> Consider putting the templates in `stregsystem/templates/mail` instead.

My initial thought was that `templates` was an www-folder and the email templates would get served as well then. I'll go ahead and move them :)

**Comment by krestenlaust** [comment]
The goal of the PR has been reached, but I haven't tested the code yet, as I'm using the web VS Codes in Github. I'll test it when I get home.

We should consider moving the `send_payment_mail` function into `mail.py`. I believe the reason it's in `utils.py`, is to avoid a circular dependency, but I'm not entirely sure. There's some code repetition in sending the emails — which could more easily be resolved by having both `send_payment_mail` and `send_welcome_mail` in the same file.

**Comment by krestenlaust** [comment]
Moving the email templates into `templates` results in the following error, when applying the data fixture,

`python.exe manage.py testserver stregsystem/fixtures/testdata.json`:
`django.template.exceptions.TemplateDoesNotExist: Problem installing fixture 'C:\Users\kress\source\repos\stregsystemet\stregsystem/fixtures\testdata.json': templates/mail/welcome.html`

Stacktrace:
```
WARNING: Not in production mode, If you are running on the server, stop right now
Creating test database for alias 'default'...
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\base.py", line 323, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\commands\testserver.py", line 37, in handle
    call_command('loaddata', *fixture_labels, **{'verbosity': verbosity})
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\base.py", line 364, in execute
    output = self.handle(*args, **options)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\commands\loaddata.py", line 72, in handle
    self.loaddata(fixture_labels)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\commands\loaddata.py", line 114, in loaddata
    self.load_label(fixture_label)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\management\commands\loaddata.py", line 181, in load_label
    obj.save(using=self.using)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\core\serializers\base.py", line 223, in save
    models.Model.save_base(self.object, using=using, raw=True, **kwargs)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\db\models\base.py", line 793, in save_base
    update_fields=update_fields, raw=raw, using=using,
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\dispatch\dispatcher.py", line 175, in send
    for receiver in self._live_receivers(sender)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\dispatch\dispatcher.py", line 175, in <listcomp>
    for receiver in self._live_receivers(sender)
  File "C:\Users\kress\source\repos\stregsystemet\stregsystem\signals.py", line 14, in after_member_save
    send_welcome_mail(instance)
  File "C:\Users\kress\source\repos\stregsystemet\stregsystem\mail.py", line 32, in send_welcome_mail
    html = render_to_string("templates/mail/welcome.html", context)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "C:\Users\kress\source\repos\stregsystemet\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: Problem installing fixture 'C:\Users\kress\source\repos\stregsystemet\stregsystem/fixtures\testdata.json': templates/mail/welcome.html

Process finished with exit code 1
```

**Comment by krestenlaust** [comment]
I resolved the issue. I had used the wrong path for the templates.

I've now also moved the send_payment_mail into mail.py.

**Review by jonasKjellerup — APPROVED** [review]
Looks good. Just needs a run through black (make sure to run it with the newest version using a recent python version, otherwise it will continue to fail in CI).

**Comment by krestenlaust** [comment]
I'm not sure what to do, I can't figure out where to read the output of the "Black formatter check", I have zero experience with Githubs CI/CD

**Comment by jonasKjellerup** [comment]
You don't really need to do anything with the output from the "Black formatter check" CI. You just need to run black formatter locally (https://github.com/psf/black) and commit the changes.

**Comment by krestenlaust** [comment]
Interesting... Are we using a different config than default for Black?

**Comment by jonasKjellerup** [comment]
The config can be find in the CI definition:
https://github.com/f-klubben/stregsystemet/blob/31d8c2a5f008cd3ed4bf66d8ba99b6b32bf1e070/.github/workflows/black.yml#L13

**Comment by krestenlaust** [comment]
It appears the formatting issues black had were unrelated to this PR, but actually originating from a commit back in November 0e1b65a. I included a commit to resolve the formatting issue. It should be ready now @jonasKjellerup, I'd probably squash, as 9 commits for this refactor is a little much 😅

**Comment by jonasKjellerup** [comment]
Oh yea; forgot about that.

@falkecarlsen will you take a look at this and merge at your convenience?

**Review by falkecarlsen — APPROVED** [review]
Thanks, great to have this decluttered a bit :shipit:

**Pull request merged**
