### PR TITLE
Made all datetimes timezone aware

### PR DESCRIPTION
**Pull request by VirtualSatai**
This will correct all the annoying warnings we get. 

We should always use `from django.utils import timezone` and `timezone.now()` to get a timestamp from now on please.

### CODE REVIEW

**Comment by DelusionalLogic** [comment]
I saw you work on this, at it seemed fine! Have you tested if anything strange happens in the DB?

**Comment by VirtualSatai** [comment]
@DelusionalLogic Not directly, will test tomorrow.

**Comment by VirtualSatai** [comment]
Looking at the changes again, they are all for queries for the database, and not actual data, so I don't really see what would be different wrt. to it.

**Comment by VirtualSatai** [comment]
Rebased with origin/next

**Comment by DelusionalLogic** [comment]
That's a good point!

**Pull request merged**
