### PR TITLE
Alcohol content in model and updated calculator

### PR DESCRIPTION
**Pull request by VirtualSatai**
This will require us to update the existing products, adding their alcohol content (in ml). 

Old list of products:
```
{13: 1.24, 14: 1.0, 29: 1.0, 42: 1.72, 47: 1.52, 54: 1.24, 65: 1.5, 66: 1.5, 1773: 1.0, 1776: 1.52, 1777: 1.52, 1779: 2.0, 1780: 2.58, 1783: 1.0, 1793: 1.0, 1794: 0.96, 22: 7.0, 23: 7.0, 41: 19.14, 53: 9.22, 63: 1.0, 64: 7.0, 1767: 1.02, 1769: 1.0, 1770: 2.0, 1802: 2.0, 1807: 6.6, 1808: 7.5, 1809: 8.3}
```

### CODE REVIEW

**Comment by fishbacon** [comment]
Can we do an initial database fixture for the existing percentages? Is that possible?

**Comment by DelusionalLogic** [comment]
I might prefer adding them in a migration (to make it automatic), although a fixture would be acceptable.

**Comment by fishbacon** [comment]
> I might prefer adding them in a migration (to make it automatic), although a fixture would be acceptable.

That is good too. As long as we can do it in a way that makes sense and updates our existing products.

**Comment by VirtualSatai** [comment]
@fishbacon I'd prefer just to do it manually, it's only 29 products after all, and then I'll verify the correctness of it (by cross referencing with the labels).

**Comment by DelusionalLogic** [comment]
I know how much you hate it when I discuss code quality, so I just went ahead and did the work myself. II hope that's ok.

The actual calculations has been extracted to a separate module (file), and has been commented thoroughly (I found it difficult to read before). I also fixed all the tests, since i changed the output format.

Overall i think the code looks better and is more readable.

**Comment by VirtualSatai** [comment]
Seems good, only thing I'd like to see changed as an easter egg surround the Ballmer Peak (https://xkcd.com/323/), but maybe Stregsystemet is too serious for stuff like that?

**Comment by DelusionalLogic** [comment]
The stregsystem is very serious

Business

**Comment by VirtualSatai** [comment]
Rebasede lige med origin/next

**Comment by VirtualSatai** [comment]
I made #92 anyway

**Comment by DelusionalLogic** [comment]
Merged

**Pull request closed without merging**
